#!/bin/sh

. "$(dirname "$0")/_/husky.sh"

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" = "main" ] || [ "$branch" = "develop" ]; then
	echo "Commiting to $branch is not allowed."
	exit 1
fi

npx lint-staged
